Develop
Kristina100070/Kristina100070.github.sprint12 pull request #1
Opened 2020-04-14 20:35 UTC by Kristina100070

2020-04-15 16:05 UTC, mrprovoker requested changes
Добрый день

Хорошая работа, нет ошибок линтера, хорошие архитектурные и структурные решения.


**Надо исправить:**
- Роут `/cards/:id` не возвращает карточку по id. По заданию данного роута не нужно было реализовывать, рекомендую удалить.
- Сейчас мидлвара в cards называется `getUsersMiddleware`, вероятнее всего должна `getCardsMiddleware`
- В репозитории есть файл, не относящийся к проекту - `.vscode`. Таких файлов в репозитории не должно быть, данные файлы обычно перечисляются в .gitignore.


Можно лучше:
- Рекомендую называть проект в README более осмысленно.
- Рекомендую заполнить секцию description в package.json
- Рекомендую мидлвары вынести в отдельную директорию `middlewares` и оттуда их экспортировать.
- Сейчас все пути `/users` имеют мидлвару getUsersMiddleware, тогда лучше будет добавить эту мидлвару в `routes/index.js`: `router.use('/users', getUsersMiddleware, users);`
- Рекомендую в app.js логически перегруппировать строки, отделяя пробелами блоки инициализации модулей, переменных, use например так:
```
const express = require('express');
const path = require('path');

const router = require('./routes/index.js');

const { PORT = 3000 } = process.env;
const app = express();

app.use(express.static(path.join(__dirname, 'public')));
app.use('/', router);
app.use('/', (req, res) => {
  res.status(404).json({ message: 'Запрашиваемый ресурс не найден' });
});

app.listen(PORT, () => {
  // eslint-disable-next-line no-console
  console.log(`App listening on port ${PORT}`);
});

```


При правках данный pull request закрывать/мерджить не надо. Все правки необходимо просто сделать новыми коммитами в этом же pull request'е.

Работу смогу принять только после устранения всех замечаний из пункта **Надо исправить**.

2020-04-16 05:20 UTC, mrprovoker requested changes
Спасибо за правки. Теперь структура стала значительно лучше.

Есть некоторые проблемы с запросами.


**Надо исправить:**
- Запрос в /users всегда возвращает `Users is not found`
- Запрос в /cards всегда возвращает `Users is not found`
- В консоль сейчас попадает `true`, связано с тем, что в catch в middlewares есть `return next(true);`. Если мы не смогли прочитать файл и отправили ошибку 500, то мы не должны дальше двигаться по цепочкам, поэтому данный next некорректный.
- Некорректно записан экспорт в middlewares. Корректнее будет `module.exports = { getCardsMiddleware, getUsersMiddleware };`. Соответственно импорт будет таким: `const { getUsersMiddleware, getCardsMiddleware } = require('../middlewares/middlewares.js');`
- Сейчас переменная pathUsers в middlewares подключает файл `cards.json`.


Можно лучше:
- Вместо require('./routes/index.js') можно проще require('./routes'), в такой записи будет по умолчанию браться файл index.js. Поэтому, например файл `middlewares/middlewares.js` можно переименовать в `middlewares/index.js` и тогда тоже можно будет проще подключать.
- В записях `res.status(200).send(req.users);` можно просто `res.send(req.users);`, так как по умолчанию статус 200.


При правках данный pull request закрывать/мерджить не надо. Все правки необходимо просто сделать новыми коммитами в этом же pull request'е.

Работу смогу принять только после устранения всех замечаний из пункта **Надо исправить**.

2020-04-16 08:45 UTC, mrprovoker commented on middlewares/index.js
> +const pathUsers = path.join(__dirname, '../data/cards.json');
Почему для path**Users** берется файл `cards.json`?

2020-04-16 10:11 UTC, Kristina100070 commented on middlewares/index.js
> +const pathUsers = path.join(__dirname, '../data/cards.json');
Исправила

2020-04-17 04:48 UTC, mrprovoker approved these changes
Спасибо, теперь все хорошо, кроме одно небольшого момента.

Переменная `const pathUsers = path.join(__dirname, '../data/users.json');` ссылатеся на файл user**s**.json, а в директории data лежит user.json.
Из-за этого запросы к /users заканчиваются статусом 500.

Прошу исправить данный момент перед мержем данного пулл реквеста.

Исправив данный момент, все пункты задания выполнены в полном объеме. Задание принято 👍

Желаю успехов в дальнейшем обучении!

2020-04-17 05:49 UTC, merged